#!/usr/bin/env python3
"""Bake the mission data files into a C++ header for the ESP32.

The seeker's trajectories and the store catalogue live in data/*.json, which
is the right format for the desktop simulator and the wrong one for a
microcontroller: cJSON builds a whole DOM, and targets.json is large enough
that the peak allocation is a real risk on a part with a few hundred KB of
DRAM. Nothing about this data changes at runtime, so it is converted once at
build time and linked in as constant arrays instead.

Usage: gen_mission_data.py <targets.json> <ammo.json> <out.hpp>
"""

import json
import sys


def emit(targets_path, ammo_path, out_path):
    with open(targets_path, encoding="utf-8") as f:
        targets = json.load(f)
    with open(ammo_path, encoding="utf-8") as f:
        ammo = json.load(f)

    count = int(targets["targetCount"])
    steps = int(targets["timeSteps"])

    tracks = targets["targets"]
    if len(tracks) != count:
        raise SystemExit(f"targetCount says {count} but {len(tracks)} tracks are present")
    for i, tr in enumerate(tracks):
        if len(tr["positions"]) != steps:
            raise SystemExit(f"track {i} has {len(tr['positions'])} points, expected {steps}")

    lines = [
        "#pragma once",
        "// Generated by tools/gen_mission_data.py — do not edit.",
        f"// Source: {targets_path.split('/')[-1]}, {ammo_path.split('/')[-1]}",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace mission_data",
        "{",
        "",
        "struct Point { float x, y; };",
        "",
        "struct Store",
        "{",
        "    const char* name;",
        "    float mass;",
        "    float drag;",
        "    float lift;",
        "};",
        "",
        f"inline constexpr int kTrackCount = {count};",
        f"inline constexpr int kNodeCount  = {steps};",
        "",
        "// [track][node], metres in the mission plane.",
        "inline constexpr Point kTracks[kTrackCount][kNodeCount] = {",
    ]

    for tr in tracks:
        pts = ", ".join(
            "{%.6ff, %.6ff}" % (float(p["x"]), float(p["y"])) for p in tr["positions"]
        )
        lines.append(f"    {{ {pts} }},")

    lines += [
        "};",
        "",
        "// Catalogue of stores the payload bay knows how to report.",
        f"inline constexpr int kStoreCount = {len(ammo)};",
        "inline constexpr Store kStores[kStoreCount] = {",
    ]

    for a in ammo:
        lines.append(
            '    { "%s", %.6ff, %.6ff, %.6ff },'
            % (a["name"], float(a["mass"]), float(a["drag"]), float(a["lift"]))
        )

    lines += [
        "};",
        "",
        "// Returns the catalogue entry for a store name, or nullptr if the bay is",
        "// configured with a name the catalogue does not contain.",
        "inline constexpr const Store* findStore(const char* name)",
        "{",
        "    for (int i = 0; i < kStoreCount; ++i)",
        "    {",
        "        const char* a = kStores[i].name;",
        "        const char* b = name;",
        "        while (*a && *a == *b) { ++a; ++b; }",
        "        if (*a == '\\0' && *b == '\\0') return &kStores[i];",
        "    }",
        "    return nullptr;",
        "}",
        "",
        "} // namespace mission_data",
        "",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"mission data: {count} tracks x {steps} nodes, {len(ammo)} stores -> {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    emit(sys.argv[1], sys.argv[2], sys.argv[3])
